#AutoEncoders

##Downloading the dataset

###ML-100K

In [1]:
!wget "http://files.grouplens.org/datasets/movielens/ml-100k.zip"
!unzip ml-100k.zip
!ls

--2023-03-17 05:35:03--  http://files.grouplens.org/datasets/movielens/ml-100k.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4924029 (4.7M) [application/zip]
Saving to: ‘ml-100k.zip’

ml-100k.zip         100%[===================>]   4.70M  5.71MB/s    in 0.8s    

2023-03-17 05:35:04 (5.71 MB/s) - ‘ml-100k.zip’ saved [4924029/4924029]

Archive:  ml-100k.zip
   creating: ml-100k/
  inflating: ml-100k/allbut.pl       
  inflating: ml-100k/mku.sh          
  inflating: ml-100k/README          
  inflating: ml-100k/u.data          
  inflating: ml-100k/u.genre         
  inflating: ml-100k/u.info          
  inflating: ml-100k/u.item          
  inflating: ml-100k/u.occupation    
  inflating: ml-100k/u.user          
  inflating: ml-100k/u1.base         
  inflating: ml-100k/u1.test         
  inflating: ml-100k/u2.base

###ML-1M

In [2]:
!wget "http://files.grouplens.org/datasets/movielens/ml-1m.zip"
!unzip ml-1m.zip
!ls

--2023-03-17 05:35:05--  http://files.grouplens.org/datasets/movielens/ml-1m.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5917549 (5.6M) [application/zip]
Saving to: ‘ml-1m.zip’

ml-1m.zip           100%[===================>]   5.64M  6.79MB/s    in 0.8s    

2023-03-17 05:35:06 (6.79 MB/s) - ‘ml-1m.zip’ saved [5917549/5917549]

Archive:  ml-1m.zip
   creating: ml-1m/
  inflating: ml-1m/movies.dat        
  inflating: ml-1m/ratings.dat       
  inflating: ml-1m/README            
  inflating: ml-1m/users.dat         
ml-100k  ml-100k.zip  ml-1m  ml-1m.zip	sample_data


##Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.optim as optim
import torch.utils.data
from torch.autograd import Variable

## Importing the dataset


In [4]:
# We won't be using this dataset.
movies = pd.read_csv('ml-1m/movies.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
users = pd.read_csv('ml-1m/users.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
ratings = pd.read_csv('ml-1m/ratings.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')

In [5]:
print(movies.head())

   0                                   1                             2
0  1                    Toy Story (1995)   Animation|Children's|Comedy
1  2                      Jumanji (1995)  Adventure|Children's|Fantasy
2  3             Grumpier Old Men (1995)                Comedy|Romance
3  4            Waiting to Exhale (1995)                  Comedy|Drama
4  5  Father of the Bride Part II (1995)                        Comedy


In [6]:
print(users.head())

   0  1   2   3      4
0  1  F   1  10  48067
1  2  M  56  16  70072
2  3  M  25  15  55117
3  4  M  45   7  02460
4  5  M  25  20  55455


In [7]:
print(ratings.head())

   0     1  2          3
0  1  1193  5  978300760
1  1   661  3  978302109
2  1   914  3  978301968
3  1  3408  4  978300275
4  1  2355  5  978824291


## Preparing the training set and the test set


**delimiter:** way to specify the seperation of delimiter tab.

To use **pytorch tensors** we will convert our pandas dataframe into numpy array.

In [8]:
training_set = pd.read_csv('ml-100k/u1.base', delimiter = '\t')
training_set = np.array(training_set, dtype = 'int')
test_set = pd.read_csv('ml-100k/u1.test', delimiter = '\t')
test_set = np.array(test_set, dtype = 'int')

In [9]:
print(training_set)

[[        1         2         3 876893171]
 [        1         3         4 878542960]
 [        1         4         3 876893119]
 ...
 [      943      1188         3 888640250]
 [      943      1228         3 888640275]
 [      943      1330         3 888692465]]


In [10]:
print(test_set)

[[        1        10         3 875693118]
 [        1        12         5 878542960]
 [        1        14         5 874965706]
 ...
 [      459       934         3 879563639]
 [      460        10         3 882912371]
 [      462       682         5 886365231]]


## Getting the number of users and movies


In [11]:
nb_users = int(max(max(training_set[:, 0], ), max(test_set[:, 0])))
nb_movies = int(max(max(training_set[:, 1], ), max(test_set[:, 1])))

## Converting the data into an array with users in lines and movies in columns


Creating the list of users and their ratings to all the movies(0 for not rated or rating as per user rated the movie).

In [12]:
def convert(data):
  new_data = []
  for id_users in range(1, nb_users + 1):
    id_movies = data[:, 1] [data[:, 0] == id_users]
    id_ratings = data[:, 2] [data[:, 0] == id_users]
    ratings = np.zeros(nb_movies)
    ratings[id_movies - 1] = id_ratings
    new_data.append(list(ratings))
  return new_data
training_set = convert(training_set)
test_set = convert(test_set)

## Converting the data into Torch tensors


**FloatTensor** class expect the data in the form of list of lists.

In [13]:
training_set = torch.FloatTensor(training_set)
test_set = torch.FloatTensor(test_set)

## Creating the architecture of the Neural Network


**SAE:** Stacked Auto Encoder

In [14]:
class SAE(nn.Module):
    def __init__(self, ):   #(self, ): After ',' it will consider the variables of the parent class
        super(SAE, self).__init__()
        #Encoder
        self.fc1 = nn.Linear(nb_movies, 20)
        self.fc2 = nn.Linear(20, 10)
        #Decoder
        self.fc3 = nn.Linear(10, 20)
        self.fc4 = nn.Linear(20, nb_movies)
        self.activation = nn.Sigmoid()
    def forward(self, x):
        x = self.activation(self.fc1(x))
        x = self.activation(self.fc2(x))
        x = self.activation(self.fc3(x))
        x = self.fc4(x)
        return x
sae = SAE()
criterion = nn.MSELoss()
optimizer = optim.RMSprop(sae.parameters(), lr = 0.01, weight_decay = 0.5)

## Training the SAE


In [15]:
nb_epoch = 200
for epoch in range(1, nb_epoch + 1):
  train_loss = 0
  s = 0.
  for id_user in range(nb_users):
    #Adding an extra dimension to create a batch, as pytorch take input as a batch.
    input = Variable(training_set[id_user]).unsqueeze(0)
    #Creating a target variable clone of the input, as autoencoder takes same input and output. 
    target = input.clone()
    if torch.sum(target.data > 0) > 0:
      output = sae(input)
      target.require_grad = False
      output[target == 0] = 0
      loss = criterion(output, target)
      mean_corrector = nb_movies/float(torch.sum(target.data > 0) + 1e-10)
      #Decides the direction of weight updates
      loss.backward()
      train_loss += np.sqrt(loss.data*mean_corrector)
      #No. of search users, that rated atleast 1 movie
      s += 1.
      #Decides the intensity of weight updates
      optimizer.step()
  print('epoch: '+str(epoch)+'loss: '+ str(train_loss/s))

epoch: 1loss: tensor(1.7715)
epoch: 2loss: tensor(1.0966)
epoch: 3loss: tensor(1.0533)
epoch: 4loss: tensor(1.0384)
epoch: 5loss: tensor(1.0308)
epoch: 6loss: tensor(1.0264)
epoch: 7loss: tensor(1.0237)
epoch: 8loss: tensor(1.0217)
epoch: 9loss: tensor(1.0207)
epoch: 10loss: tensor(1.0196)
epoch: 11loss: tensor(1.0191)
epoch: 12loss: tensor(1.0180)
epoch: 13loss: tensor(1.0180)
epoch: 14loss: tensor(1.0174)
epoch: 15loss: tensor(1.0173)
epoch: 16loss: tensor(1.0169)
epoch: 17loss: tensor(1.0167)
epoch: 18loss: tensor(1.0162)
epoch: 19loss: tensor(1.0165)
epoch: 20loss: tensor(1.0162)
epoch: 21loss: tensor(1.0161)
epoch: 22loss: tensor(1.0158)
epoch: 23loss: tensor(1.0158)
epoch: 24loss: tensor(1.0156)
epoch: 25loss: tensor(1.0157)
epoch: 26loss: tensor(1.0155)
epoch: 27loss: tensor(1.0154)
epoch: 28loss: tensor(1.0150)
epoch: 29loss: tensor(1.0140)
epoch: 30loss: tensor(1.0120)
epoch: 31loss: tensor(1.0097)
epoch: 32loss: tensor(1.0091)
epoch: 33loss: tensor(1.0053)
epoch: 34loss: tens

## Testing the SAE


In [16]:
test_loss = 0
s = 0.
for id_user in range(nb_users):
  input = Variable(training_set[id_user]).unsqueeze(0)
  target = Variable(test_set[id_user]).unsqueeze(0)
  if torch.sum(target.data > 0) > 0:
    output = sae(input)
    target.require_grad = False
    output[target == 0] = 0
    loss = criterion(output, target)
    mean_corrector = nb_movies/float(torch.sum(target.data > 0) + 1e-10)
    test_loss += np.sqrt(loss.data*mean_corrector)
    s += 1.
    print(output)
print('test loss: '+str(test_loss/s))

tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[3.1249, 2.4461, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[4.1694, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<IndexPutBackward0>)
tensor([[0.0000, 2.8028, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       grad_fn=<IndexPutBackward0